<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/** @var $block \Magefan\Security\Block\Adminhtml\Dashboard\SecurityStatus */
/** @var $escaper \Magento\Framework\Escaper */
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<div class="horizontal-bar">
    <div class="dashboard-item-title">
        <?= $escaper->escapeHtml(__('Security Status')) ?>
        <?php if ($block->isEnabled()) { ?>
            (<a href="<?= $escaper->escapeUrl($block->getUrl('mfsecurity/security/dashboard')) ?>">
                <?= $escaper->escapeHtml(__('View report')) ?>
            </a>)
        <?php } ?>
    </div>
    <?php if ($block->isEnabled()) { ?>
        <div class="content">
            <div data-stepped-bar='<?= $escaper->escapeHtmlAttr($block->getSecurityStatus()) ?>'></div>
        </div>
    <?php } else { ?>
        <br/>
        <div class="message message-warning warning">
            <div data-ui-id="messages-message-warning">
                <?php
                $url = $escaper->escapeUrl(
                    $block->getUrl('adminhtml/system_config/edit', ['section' => 'mfsecurity'])
                );
                $linkText = __('Stores > Configuration > Magefan Extensions > Security');
                $link = '<a href="' . $url . '">' . $linkText . '</a>';
                ?>
                <?= $escaper->escapeHtml(__('Magefan Security is disabled. Please enable it in %1.', $link), ['a']) ?>
            </div>
        </div>
   <?php } ?>
</div>
